syntax on

set expandtab
set tabstop=2
set shiftwidth=2
set wildmode=list:longest
let g:netrw_liststyle=3
set splitbelow
set splitright
set dir=/tmp
set tabpagemax=100

" auto read files that are change outside of the vim session (when you run a command in vim)
set autoread

" Makes search act like search in modern browsers
set incsearch

" turn off swap / auto backup
set nobackup
set nowb
set noswapfile

" install Vim-Plug -- https://github.com/junegunn/vim-plug/wiki/tips#automatic-installation
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" install plugins
call plug#begin('~/.vim/plugged') " Inialize Plug

Plug 'ctrlpvim/ctrlp.vim'
Plug 'vim-airline/vim-airline'
Plug 'preservim/nerdtree'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'airblade/vim-gitgutter'

call plug#end()

" strip trailing whitespace on save
autocmd BufWritePre * :%s/\s\+$//e

" copy to the clipboard when using yy: linux
" set clipboard=unnamedplus

" copy to the clipboard when using yy: mac
set clipboard=unnamed


" The Silver Searcher
if executable('ag')
  " Use ag over grep
  set grepprg=ag\ --nogroup\ --nocolor

  " Use ag in CtrlP for listing files. Lightning fast and respects .gitignore
  let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'

  " ag is fast enough that CtrlP doesn't need to cache
  let g:ctrlp_use_caching = 0

  " bind \ (backward slash) to grep shortcut
  command -nargs=+ -complete=file -bar Ag silent! grep! <args>|cwindow|redraw!
endif

autocmd BufRead *.sql set filetype=mysql

" Keyboard Shortcuts
map <C-n> :NERDTreeFocus<CR>
