return {
    {
        'MeanderingProgrammer/render-markdown.nvim',
        dependencies = { 
            'nvim-treesitter/nvim-treesitter',
            'nvim-tree/nvim-web-devicons'
        },
        opts = {
            file_types = { "markdown", "Avante" },
            code = {
                enabled = true,
                sign = true,
                style = 'full',
                position = 'left',
                language_pad = 0,
                language_name = true,
                disable_background = { 'diff' },
                width = 'full',
                left_margin = 0,
                left_pad = 0,
                right_pad = 0,
                min_width = 0,
                border = 'thin',
                above = '▄',
                below = '▀',
                highlight = 'RenderMarkdownCode',
                highlight_inline = 'RenderMarkdownCodeInline',
            },
            heading = {
                enabled = true,
                sign = true,
                position = 'overlay',
                icons = { '󰲡 ', '󰲣 ', '󰲥 ', '󰲧 ', '󰲩 ', '󰲫 ' },
                signs = { '󰫎 ' },
                width = 'full',
                left_margin = 0,
                left_pad = 0,
                right_pad = 0,
                min_width = 0,
                border = false,
                border_prefix = false,
                above = '▄',
                below = '▀',
                backgrounds = {
                    'RenderMarkdownH1Bg',
                    'RenderMarkdownH2Bg',
                    'RenderMarkdownH3Bg',
                    'RenderMarkdownH4Bg',
                    'RenderMarkdownH5Bg',
                    'RenderMarkdownH6Bg',
                },
                foregrounds = {
                    'RenderMarkdownH1',
                    'RenderMarkdownH2',
                    'RenderMarkdownH3',
                    'RenderMarkdownH4',
                    'RenderMarkdownH5',
                    'RenderMarkdownH6',
                },
            },
            dash = {
                enabled = true,
                icon = '─',
                width = 'full',
                highlight = 'RenderMarkdownDash',
            },
            bullet = {
                enabled = true,
                icons = { '•', '◦', '▸', '▹' },
                ordered_icons = { '1.', '2.', '3.', '4.', '5.', '6.', '7.', '8.', '9.' },
                left_pad = 0,
                right_pad = 0,
                highlight = 'RenderMarkdownBullet',
            },
            checkbox = {
                enabled = true,
                unchecked = {
                    icon = '󰄱',
                    highlight = 'RenderMarkdownUnchecked',
                    scope_highlight = nil,
                },
                checked = {
                    icon = '󰱒',
                    highlight = 'RenderMarkdownChecked',
                    scope_highlight = nil,
                },
                custom = {
                    todo = { raw = '[-]', rendered = '󰥔', highlight = 'RenderMarkdownTodo', scope_highlight = nil },
                    inprogress = { raw = '[~]', rendered = '󰡖', highlight = 'RenderMarkdownInProgress', scope_highlight = nil },
                    cancelled = { raw = '[_]', rendered = '󰩺', highlight = 'RenderMarkdownCancelled', scope_highlight = nil },
                    forwarded = { raw = '[>]', rendered = '󰒊', highlight = 'RenderMarkdownForwarded', scope_highlight = nil },
                    scheduled = { raw = '[<]', rendered = '󰃰', highlight = 'RenderMarkdownScheduled', scope_highlight = nil },
                    question = { raw = '[?]', rendered = '󰞋', highlight = 'RenderMarkdownQuestion', scope_highlight = nil },
                    important = { raw = '[!]', rendered = '󰀨', highlight = 'RenderMarkdownImportant', scope_highlight = nil },
                    star = { raw = '[*]', rendered = '󰓎', highlight = 'RenderMarkdownStar', scope_highlight = nil },
                    quote = { raw = '["]', rendered = '󱆨', highlight = 'RenderMarkdownQuote', scope_highlight = nil },
                    location = { raw = '[l]', rendered = '󰍎', highlight = 'RenderMarkdownLocation', scope_highlight = nil },
                    bookmark = { raw = '[b]', rendered = '󰃀', highlight = 'RenderMarkdownBookmark', scope_highlight = nil },
                    information = { raw = '[i]', rendered = '󰋽', highlight = 'RenderMarkdownInformation', scope_highlight = nil },
                    savings = { raw = '[$]', rendered = '󰈸', highlight = 'RenderMarkdownSavings', scope_highlight = nil },
                    idea = { raw = '[I]', rendered = '󰌵', highlight = 'RenderMarkdownIdea', scope_highlight = nil },
                    pros = { raw = '[p]', rendered = '󰔓', highlight = 'RenderMarkdownPros', scope_highlight = nil },
                    cons = { raw = '[c]', rendered = '󰔑', highlight = 'RenderMarkdownCons', scope_highlight = nil },
                    fire = { raw = '[f]', rendered = '󰈸', highlight = 'RenderMarkdownFire', scope_highlight = nil },
                    key = { raw = '[k]', rendered = '󰌆', highlight = 'RenderMarkdownKey', scope_highlight = nil },
                    win = { raw = '[w]', rendered = '󰜺', highlight = 'RenderMarkdownWin', scope_highlight = nil },
                    up = { raw = '[u]', rendered = '󰁝', highlight = 'RenderMarkdownUp', scope_highlight = nil },
                    down = { raw = '[d]', rendered = '󰁅', highlight = 'RenderMarkdownDown', scope_highlight = nil },
                },
            },
            quote = {
                enabled = true,
                icon = '▌',
                repeat_linebreak = false,
                highlight = 'RenderMarkdownQuote',
            },
            pipe_table = {
                enabled = true,
                preset = 'heavy',
                style = 'full',
                cell = 'padded',
                padding = 1,
                min_width = 0,
                border = {
                    '┏', '┳', '┓', '┣', '╋', '┫', '┗', '┻', '┛',
                    '┃', '┃', '┃',
                },
                alignment_indicator = '━',
                head = 'RenderMarkdownTableHead',
                row = 'RenderMarkdownTableRow',
                filler = 'RenderMarkdownTableFill',
            },
            callout = {
                note = { raw = '[!NOTE]', rendered = '󰋽 Note', highlight = 'RenderMarkdownInfo' },
                tip = { raw = '[!TIP]', rendered = '󰌶 Tip', highlight = 'RenderMarkdownSuccess' },
                important = { raw = '[!IMPORTANT]', rendered = '󰅾 Important', highlight = 'RenderMarkdownHint' },
                warning = { raw = '[!WARNING]', rendered = '󰀪 Warning', highlight = 'RenderMarkdownWarn' },
                caution = { raw = '[!CAUTION]', rendered = '󰳦 Caution', highlight = 'RenderMarkdownError' },
                abstract = { raw = '[!ABSTRACT]', rendered = '󰨸 Abstract', highlight = 'RenderMarkdownInfo' },
                summary = { raw = '[!SUMMARY]', rendered = '󰨸 Summary', highlight = 'RenderMarkdownInfo' },
                tldr = { raw = '[!TLDR]', rendered = '󰨸 TL;DR', highlight = 'RenderMarkdownInfo' },
                info = { raw = '[!INFO]', rendered = '󰋽 Info', highlight = 'RenderMarkdownInfo' },
                todo = { raw = '[!TODO]', rendered = '󰗡 Todo', highlight = 'RenderMarkdownInfo' },
                hint = { raw = '[!HINT]', rendered = '󰌶 Hint', highlight = 'RenderMarkdownSuccess' },
                success = { raw = '[!SUCCESS]', rendered = '󰄬 Success', highlight = 'RenderMarkdownSuccess' },
                check = { raw = '[!CHECK]', rendered = '󰄬 Check', highlight = 'RenderMarkdownSuccess' },
                done = { raw = '[!DONE]', rendered = '󰄬 Done', highlight = 'RenderMarkdownSuccess' },
                question = { raw = '[!QUESTION]', rendered = '󰘥 Question', highlight = 'RenderMarkdownWarn' },
                help = { raw = '[!HELP]', rendered = '󰘥 Help', highlight = 'RenderMarkdownWarn' },
                faq = { raw = '[!FAQ]', rendered = '󰘥 FAQ', highlight = 'RenderMarkdownWarn' },
                attention = { raw = '[!ATTENTION]', rendered = '󰀪 Attention', highlight = 'RenderMarkdownWarn' },
                failure = { raw = '[!FAILURE]', rendered = '󰅖 Failure', highlight = 'RenderMarkdownError' },
                fail = { raw = '[!FAIL]', rendered = '󰅖 Fail', highlight = 'RenderMarkdownError' },
                missing = { raw = '[!MISSING]', rendered = '󰅖 Missing', highlight = 'RenderMarkdownError' },
                danger = { raw = '[!DANGER]', rendered = '󱐌 Danger', highlight = 'RenderMarkdownError' },
                error = { raw = '[!ERROR]', rendered = '󱐌 Error', highlight = 'RenderMarkdownError' },
                bug = { raw = '[!BUG]', rendered = '󰨰 Bug', highlight = 'RenderMarkdownError' },
                example = { raw = '[!EXAMPLE]', rendered = '󰉹 Example', highlight = 'RenderMarkdownHint' },
                quote = { raw = '[!QUOTE]', rendered = '󱆨 Quote', highlight = 'RenderMarkdownQuote' },
                cite = { raw = '[!CITE]', rendered = '󱆨 Cite', highlight = 'RenderMarkdownQuote' },
            },
            link = {
                enabled = true,
                image = '󰥶 ',
                email = '󰊫 ',
                hyperlink = '󰌹 ',
                highlight = 'RenderMarkdownLink',
                wiki = { icon = '󱗖 ', highlight = 'RenderMarkdownWikiLink' },
                custom = {
                    web = { pattern = '^http[s]?://', icon = '󰖟 ', highlight = 'RenderMarkdownWebLink' },
                },
            },
            sign = {
                enabled = true,
                highlight = 'RenderMarkdownSign',
            },
            indent = {
                enabled = false,
                per_level = 2,
                skip_level = 1,
                skip_heading = false,
            },
            smooth_scroll = {
                enabled = true,
                duration = 0.3,
                fps = 60,
            },
        },
        ft = { "markdown" },
    }
}