k9s:
  liveViewAutoRefresh: false
  refreshRate: 2
  maxConnRetry: 5
  readOnly: false
  noExitOnCtrlC: false
  ui:
    enableMouse: false
    headless: false
    crumbsless: false
    reactive: false
    noIcons: false
  logger:
    tail: 200
    buffer: 5000
    sinceSeconds: -1
    textWrap: false
    showTime: false
