
SCRIPT_DIR=$0:A:h

HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000

# unsetopt autocd extendedglob nomatch
bindkey -v

zstyle :compinstall filename '/home/mat/.zshrc'

bindkey -v '^?' backward-delete-char # backspace behaviour aligned with vim behaviour

# enable reverse search
bindkey -v
# bindkey '^R' history-incremental-search-backward

# brew, mac only
if [[ `uname | grep Darwin` ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

eval "$(starship init zsh)"


## fzf
# Open in tmux popup if on tmux, otherwise use --height mode
export FZF_DEFAULT_OPTS='--height 40% --tmux bottom,40% --layout reverse --border top'
source <(fzf --zsh)


## atuin
eval "$(atuin init zsh --disable-up-arrow)"


# if [[ `which gh` ]]; then
#   eval "$(gh completion -s zsh)"
#
#   function gh-work() {
#     rm ~/.config/gh/hosts.yml &> /dev/null || true
#     ln -s ~/.config/gh/hosts-jc.yml ~/.config/gh/hosts.yml
#     echo "gh is now setup with work credentials"
#   }
#
#   function gh-personal() {
#     rm ~/.config/gh/hosts.yml &> /dev/null || true
#     ln -s ~/.config/gh/hosts-personal.yml ~/.config/gh/hosts.yml
#     echo "gh is now setup with personal credentials"
#   }
# fi

# rbenv
# if [[ `which rbenv` ]]; then
#     export PATH="$HOME/.rbenv/bin:$PATH"
#     eval "$(rbenv init - zsh)"
# fi

# these are so friggin slow... let's not and find something better
# pyenv
#if [[ `which pyenv` ]]; then
#  export PYENV_ROOT="$HOME/.pyenv"
#  export PATH="$PYENV_ROOT/bin:$PATH"
#  eval "$(pyenv init --path)"
#  eval "$(pyenv init -)"
#fi

#if [[ `which pyenv-virtualenv` ]]; then
#  eval "$(pyenv virtualenv-init -)"
#fi

if [[ `which jenv` ]]; then
    export PATH="$HOME/.jenv/bin:$PATH"
    eval "$(jenv init -)"
fi

if [ -d $HOME/.cargo ]; then
    source "$HOME/.cargo/env"                                                                  │
fi

# ssh-agent
eval $(ssh-agent) > /dev/null # thanks, I hate it.


# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion


export PATH="$HOME/bin:$PATH"

. $SCRIPT_DIR/../shell/aliases.sh
. $SCRIPT_DIR/../shell/environment.sh

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

