
# If not running interactively, don't do anything
[[ $- != *i* ]] && return

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# source bash configs
. $SCRIPT_DIR/prompt_config
. $SCRIPT_DIR/color_config
. $SCRIPT_DIR/aliases
. $SCRIPT_DIR/environment

# bash-completion
[[ $PS1 && -f /usr/share/bash-completion/bash_completion ]] && \
    . /usr/share/bash-completion/bash_completion

set -o ignoreeof
set -o vi
