echo "running ~/.bash_profile"
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# source bash configs
. $SCRIPT_DIR/prompt_config
. $SCRIPT_DIR/color_config
. $SCRIPT_DIR/aliases
. $SCRIPT_DIR/environment

