#!/bin/bash
. lib/helpers.sh

# Secretive: SSH keys in the Mac's Secure Enclave. mac-only.
#
# We use it for ONE thing: a per-machine, non-exportable git signing key that
# agent (Claude) sessions sign with unattended — no 1Password prompt, and the
# key can never be exfiltrated (worst case malware signs while this Mac is
# unlocked; revoke = delete the key on GitHub). Mat's own terminal keeps
# signing with the 1Password key, so the two attestations stay distinct:
# 1P key = "Mat was present", Secretive key = "made on Mat's machine".
#
# Wiring (all generated here, per machine — the enclave key can't leave the
# chip, so every Mac runs this and registers its own key):
#   ~/.ssh/secretive-agent-signing.pub   the key, extracted from the agent
#   ~/.gitconfig-agent-signing           turns signing on with that key
#   agent-config/settings.json          agent sessions include that file via
#                                        GIT_CONFIG env; missing file = unsigned
#                                        commits (safe default on a Mac that
#                                        hasn't run this yet)
#   ssh/allowed_signers (dotfiles)       trust for verification (%G? = G)
#   GitHub                               add as a SIGNING key on every account
#                                        used from this machine
SECRETIVE_SOCK="$HOME/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/socket.ssh"
KEY_NAME="agent-signing"
PUB_FILE="$HOME/.ssh/secretive-agent-signing.pub"
GITCONFIG_FILE="$HOME/.gitconfig-agent-signing"

function setup_secretive() {
  if ! is_mac; then
    print_with_color $GREEN 'Secretive is mac-only, skipping...'
    return
  fi

  if [ ! -d /Applications/Secretive.app ]; then
    brew install --cask secretive
  fi

  # Key creation is manual — Secretive has no CLI. The auth policy is the point:
  # "not required" is what lets agents sign unattended.
  if [ ! -S "$SECRETIVE_SOCK" ] || ! SSH_AUTH_SOCK="$SECRETIVE_SOCK" ssh-add -L 2>/dev/null | grep -q .; then
    open -a Secretive
    print_with_color $YELLOW "In Secretive: create a key named '$KEY_NAME', authentication NOT required. Press enter when done."
    read -r
  fi

  local pub
  pub=$(SSH_AUTH_SOCK="$SECRETIVE_SOCK" ssh-add -L | grep -i "$KEY_NAME" || true)
  if [ -z "$pub" ]; then
    # A single key with a different name is fine; more than one needs the name.
    pub=$(SSH_AUTH_SOCK="$SECRETIVE_SOCK" ssh-add -L)
    if [ "$(printf '%s\n' "$pub" | wc -l)" -ne 1 ]; then
      print_with_color $RED "Couldn't pick a key: none named '$KEY_NAME' and more than one in the agent. Rename it in Secretive and re-run."
      return 1
    fi
  fi

  mkdir -p "$HOME/.ssh"
  printf '%s\n' "$pub" > "$PUB_FILE"
  print_with_color $GREEN "wrote $PUB_FILE"

  # git reads a public-key file here and signs via the agent (secretive-sign
  # wraps ssh-keygen with Secretive's socket, leaving SSH_AUTH_SOCK alone).
  cat > "$GITCONFIG_FILE" <<EOF
# Generated by dotfiles/secretive/setup_secretive.sh — do not edit; re-run it.
# Included by agent sessions (agent-config/settings.json GIT_CONFIG env) to
# sign commits with this machine's Secure Enclave key.
[commit]
  gpgsign = true
[user]
  signingkey = $PUB_FILE
[gpg "ssh"]
  program = $HOME/dotfiles/bin/secretive-sign
EOF
  print_with_color $GREEN "wrote $GITCONFIG_FILE"

  # Trust the key for verification on all machines: the line lives in the
  # tracked allowed_signers, one per machine — commit the change.
  local email signer_line
  email=$(git config user.email)
  signer_line="$email $(printf '%s\n' "$pub" | awk '{print $1, $2}')"
  if ! grep -qF "$(printf '%s\n' "$pub" | awk '{print $2}')" "$(pwd)/ssh/allowed_signers"; then
    printf '%s\n' "$signer_line" >> "$(pwd)/ssh/allowed_signers"
    print_with_color $YELLOW "appended this machine's key to ssh/allowed_signers — commit the dotfiles change"
  fi

  # Register as a SIGNING key (not auth) on GitHub — repeat per account used
  # from this machine (e.g. the work account on the work Mac).
  local title="$KEY_NAME $(hostname -s)"
  if gh ssh-key add "$PUB_FILE" --type signing --title "$title" 2>/dev/null; then
    print_with_color $GREEN "added to GitHub ($(gh api user -q .login)) as signing key '$title'"
  else
    print_with_color $YELLOW "gh couldn't add the signing key (scope?). Either:"
    print_with_color $YELLOW "  gh auth refresh -h github.com -s admin:ssh_signing_key   # then re-run"
    print_with_color $YELLOW "  or paste $PUB_FILE at https://github.com/settings/ssh/new (type: Signing Key)"
  fi
}

print_with_color $YELLOW 'Setup Secretive (agent git signing)? (y/n)'
read yn
case $yn in
  yes|Yes|YES|y|Y ) setup_secretive;;
  * ) print_with_color $GREEN 'skipping...';;
esac
